services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    image: etl_marinadaggdjur_dwc:latest
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    command: ["python", "-m", "marinadaggdjur.main", "etl_configs/tumlare.yml"]
